### ISSUE TITLE
Design Event Bus as service communication mechanism

### ISSUE THREAD

**Issue by wrichter** [sa-mw-dach/OpenDJ#15]
E.G. Apache Kafka / AMQ Streams or AMQ Pub/Sub

**Comment by DanielFroehlich** [comment]
depends on #24. I did have a session with @ortwinschneider  on Kafka, and the more I see, the more I like it. I am pretty confident we will use it.

**Comment by DanielFroehlich** [comment]
We go with Kafka, as it can also nicely serve as persitence, is meanwhile a Red Hat Product and we would like to play with new technology.
