### ISSUE TITLE
How to describe event bus interfaces?

### ISSUE THREAD

**Issue by wrichter** [sa-mw-dach/OpenDJ#24]
For HTTP interfaces, we can use a Swagger/OpenAPI definition, which can be rendered into a Test UI and used for scaffolding of implementations and client code. Can we use something equivalent for event bus based interfaces(#16)?

**Comment by wrichter** [comment]
In today's integration quarterly update, they pointed to https://www.asyncapi.com

**Comment by DanielFroehlich** [comment]
It is not only event bus interfaces, but interfaces in general. 
How do we describe interfaces?

**Comment by DanielFroehlich** [comment]
GRPC / Protobuffers could  also be an option.
Nice lean, and async is easy, simple one way rpc call with no response, ore even a stream of events as response back

https://grpc.io/docs/guides/

OpenAPI vs. gRPC comparison:
https://medium.com/apis-and-digital-transformation/openapi-and-grpc-side-by-side-b6afb08f75ed

**Comment by wrichter** [comment]
I find gRPC interesting, Do you know the extent of gRPC Support in the RH Toolchain? Wrt event/AsyncAPI interfaces, I think AsyncAPI is a better representation than a one-way gRPC since it has a native concept of topic spaces.

**Comment by DanielFroehlich** [comment]
I have no clue. @ortwinschneider maybe?
My understanding is that it uses HTTP/2 as transport, and good news - THAT is supported ingress with OpenShift V3.11: https://access.redhat.com/solutions/2274201

**Comment by wrichter** [comment]
OpenAPI should be independent of a transport protocol version, so I believe HTTP/2 should also work for an HTTP interface defined via OpenAPI. Reading about this, a new aspect came to my mind - how to describe WebSocket interfaces?? This is likely not gRPC (since we cannot expect browsers to have support for it), but also not HTTP Verbs/status codes either (so OpenAPI is maybe not a good fit: https://github.com/OAI/OpenAPI-Specification/issues/523)

**Comment by DanielFroehlich** [comment]
I tried to use OpenAPI to create the analysis model. 
From that experience: I don't like OpenAPI. It is far too fixed on REST and HTTP, so probably not suitable to describe event bus interfaces.

I will now experiment with PlantUML: use good old interfaces for sync interactions, and classes describing async events. That did work already in a white board session with @ortwinschneider, so let me try to get code it....

**Comment by wrichter** [comment]
Have you looked at AsyncAPI yet?

**Comment by DanielFroehlich** [comment]
Let me start an assessment of the Option "AsyncAPI" so we can later copy/paste to an architectural decision document. Please edit this note as desired!

## Option: "Use Async.API"
AsyncAPI is an extension/variation of OpenAPI by adding async/event handling capabilities.
[Details here](https://www.asyncapi.com). The [Getting Started doc](https://www.asyncapi.com/docs/getting-started)  is a quick read while providing good overview.

Pro:
1. open to different protocols (websockets, kafka, amqp, mqtt)
1. very close to OpenAPI, that we will probably use for sync interfaces. We could e.g. re-use schemas for objects that appear on both sync and async apis.
1. potential future support in RH tooling (currently under evaluation). The slides for [this summit talk](https://summit.redhat.com/conference/sessions?p1=eyJzcGVha2VyIjpbXSwidGltZXNsb3QiOltdLCJkYXkiOltdLCJyb29tIjpbXSwibG9jYXRpb24iOltdLCJzdGFydCI6IiIsImZpbmlzaCI6IiIsInBhZ2VudW1iZXIiOjEsImNhdGVnb3JpZXMiOnt9LCJrZXl3b3JkIjoiYXN5bmNocm9ub3VzIGFwaXMifQ%3D%3D) might give additional insights (did not manage to attend it).
1. also makes suggestions how to structure topics for events, which could be used independent of the API description format/tools

Contra:
1. It is currently Version 2.0.0-rc1,  so this is the bleeding edge of technology.
1. Small Community - [github project](https://github.com/asyncapi) has only 9 members
1. limited tooling support, VSCode extension "openapi-lint" provides limited validation capabilities, but only for V1.2.0.

Open Questions:
1. I think we should experiment with this, e.g. define a simple async api, use it to generate prducer/consumer code against kafka and see how it works.

**Comment by DanielFroehlich** [comment]
## Option: "Use PlantUML"

### Description
PlantUML can be used to describe async events.
High level in e.g. a component diag could look like this:  

![highlevel](http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.github.com/sa-mw-dach/OpenDJ/master/docs/00project/eventBusDescription/eventsAsComponentDiag.puml)



On a more fine grained level, it could look like this:
![highlevel](http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.github.com/sa-mw-dach/OpenDJ/master/docs/00project/eventBusDescription/eventsAsClassDiag.puml)


### Pro:
1. no new tool, we use plantuml already

### Contra:
1. nothing can be generated out of this.
1. current design does not include topic space, only event/message format. 


### Open Questions
1. Unclear if multiple event types can be aggregated to an "interface description".

**Comment by wrichter** [comment]
Edit: Did add some aspects to the evaluations above

**Comment by DanielFroehlich** [comment]
I vote for a combination: we go with AsyncAPI where possible, and if the interface is still to vague, we go with PlantUML or simply textual description
