### ISSUE TITLE
Agree on degree of RESTfulness in HTTP APIs

### ISSUE THREAD

**Issue by wrichter** [sa-mw-dach/OpenDJ#25]
Not sure if full REST actually solves problems for us or creates new problems:
* swagger/openAPI can’t do HATEOAS: https://github.com/OAI/OpenAPI-Specification/issues/577
* we dont need to decouple client and server implementation
* using well known http verbs is probably a good idea (use DELETE to delete instead of POST)
*...

**Comment by DanielFroehlich** [comment]
I think going full HATEOS is overkill for OpenDJ, so I vote for going with the suggested well known http verbs approach.
