### ISSUE TITLE
Consider classification of songs in collaboration with the AI/KI fraction in the SA community

### ISSUE THREAD

**Issue by wrichter** [sa-mw-dach/OpenDJ#27]
created by Michael Leibfried

**Comment by DanielFroehlich** [comment]
What I would prefer first in regards to AI/KI/ML would be a Mixer-Module, able to mix the transition from "Bohemian Rhapsody" to "Dancing Queen".
I think this is far out of reach of this project for the moment, so I close it for now and we can re-open it maybe later.
