### ISSUE TITLE
Decide on UML Tooling

### ISSUE THREAD

**Issue by DanielFroehlich** [sa-mw-dach/OpenDJ#29]
We need to decide on Project Tooling used for:
1. Modelling (Architecture, Design, DataModel) - UML? Modelio?
2. Project Management (Epics, Use Storie, Sprint Planning etc) - Trello? GithUb?
3.  ...

**Comment by wrichter** [comment]
Suggest to look at http://plantuml.com/ which allows generating uml diagrams from easily diffable/writable Text docs.

**Comment by wrichter** [comment]
For any planning I would stick to GitHub projects until the limitations become too apparent - that way information is located at a single point

**Comment by DanielFroehlich** [comment]
Regarding plantUML: I do like the approach in general, and support into vscode or atom.
Downside:  code generation seems to be a problem. Not sure how much much code we could generate. Maybe some SQL/JSON/Swagger/Java Interfaces.
Probably depends on wether we go more Model Driven or more Test Driven.

**Comment by DanielFroehlich** [comment]
@ortwinschneider , would love to hear your thoughts on Modelling tool!

**Comment by wrichter** [comment]
Ah, i’m a firm nonbeliever in model driven + code gen due to my BPMN history. I haven’t seen roundtripping work, and actually modeling behavior and details was equally complex as simply coding it (with some exaggeration). Therefore in my mind I’ve limited model-driven + code gen to isolated aspects such as stub/skeleton generation from API defs, etc.

**Comment by DanielFroehlich** [comment]
I do have some good experience with just forward only generation, e.g. in SQL / Java Data TransferObjects area. 
But I am inclided to say that we dont need that here as often. And JSON Data Modelling can be simply done with prototypes, i.e. a bunch of JSON files giving examples.
So just for the better team working experience, merging etc. I am trending to go with plantUML, but lets see what others are going to add to the discussion.

**Comment by DanielFroehlich** [comment]
Switched topic from "Decide on Tooling" to "Decide on UML Tooling" tooling, need to create new issue for each tool we need.

**Comment by DanielFroehlich** [comment]
There are tools/projects to generate PlantUML from Swagger or  GRPC. For me, thats the final argument to decide PRO plantUML.
So: PlantUML it is!
