### ISSUE TITLE
Agree on team roles

### ISSUE THREAD

**Issue by DanielFroehlich** [sa-mw-dach/OpenDJ#34]
Which roles do we need, and who has which roles?
 Candiates:
- Product Owner
- Project manager / Scrum Master
- Lead UX 
- Lead Architect
- Lead QS
- ...

**Comment by wrichter** [comment]
https://m.xkcd.com/2141/

**Comment by DanielFroehlich** [comment]
As this is a volunteer project, I think we can drop this ticket. Whoevery joins and contributes will do that in a role suitable to his capabilities. If someone disagrees, please re-open this issue.
