### ISSUE TITLE
frontend uses hardcoded URLs to services

### ISSUE THREAD

**Issue by DanielFroehlich** [sa-mw-dach/OpenDJ#35]
Thats not good, makes it impossible to move to different environments.
Example:
OpenDJ/frontend/app/src/app/home/home.page.ts:
...
    const playlistUrl = 'http://playlist-dfroehli-opendj dev.apps.ocp1.hailstorm5.coe.muc.redhat.com/api/v1/';
...

**Comment by DanielFroehlich** [comment]
Hi Column! Could you please make this an ENV Variable so we can set it from outside? Thx Dan

**Comment by col1985** [comment]
@DanielFroehlich yep no problem

**Comment by DanielFroehlich** [comment]
Moved to current project so that I can close "01 - Secure Hackathon Work"

**Comment by DanielFroehlich** [comment]
Will be fixed by new frontend impl by @ortwinschneider
