### ISSUE TITLE
decide on UX/UI design/prototype tool

### ISSUE THREAD

**Issue by DanielFroehlich** [sa-mw-dach/OpenDJ#39]
OpenDJ needs several screens. To facilitate communication between UX design and implementation, a tool would be good.

**Comment by DanielFroehlich** [comment]
Based on [this article](https://medium.theuxblog.com/11-best-prototyping-tools-for-ui-ux-designers-how-to-choose-the-right-one-c5dc69720c47), i looked into 

A: Adobe XD
+ offline
+ free usage for single project
+ rather intuitive
+ can start from scratch (without design)
- only binary project to share on github
- commercial
- no html5 output

B: InVision
+ export to html5
- need to have a design 
- online
- not intuitive to me
- commercial

C: Simply HTML5
+ direct use for implemtation
- not intuitive

D: Textual Description
+ Works for everybody
- not visually

**Comment by DanielFroehlich** [comment]
@col1985 , do you have any recommendations for UX/UI tools? Open Source and collaborative preferred? Thx Dan

**Comment by DanielFroehlich** [comment]
@LeibfriedM @mmetting As you also have some UX/UI experience, any thoughts on a frontend prototyping tool?

**Comment by col1985** [comment]
@DanielFroehlich Adobe Xd is a good tool to use. I also like Sketch but license is required. InVision sounds interesting never used that tool.

**Comment by col1985** [comment]
I also look at Ionic App Creater but this uses an outdated version of Ionic and requires a subscription fee.

**Comment by DanielFroehlich** [comment]
Adobe XD requires a license, but that is free of charge. So until someone shows me a good open source alternative, we go with Adobe XD

**Comment by DanielFroehlich** [comment]
I just saw that one could also use PlantUML to visualize a UI prototype:
http://plantuml.com/de/salt
Not that sexy and interactive as Adobe XD, but could do the job.

**Comment by SiddharthSimharaju** [comment]
Hello @DanielFroehlich,
I would have recommended you to use FIGMA. It's a great tool similar to Adobe XD and with group collabs.
