### ISSUE TITLE
Decide on UI Framework

### ISSUE THREAD

**Issue by DanielFroehlich** [sa-mw-dach/OpenDJ#46]

**Comment by DanielFroehlich** [comment]
Interesting Read: Comparison of Vue vs. React vs. Angular: https://www.codeinwp.com/blog/angular-vs-vue-vs-react/

**Comment by ortwinschneider** [comment]
# Option A: Ionic/Angular
## Description
Use Ionic as UI Component Library with Angular as core framework.
See prototype in folder *TODO* insert here

## Pro
1. Widley adopted, lots of skill in the team
1. Security - CORS / DOM Security embedded, Sanitizer etc.
1. VueJS and React support in development
1. Easy transition to native apps (e.g. iOS/Android)
1. Many native device plugins (TouchID/FaceID, Camera etc...)
1. Switchable look and feel for IOS / Android / Material Design for Browser
1. Service Worker / PWA
1. Existing KnowHow/Expierence in the team


## Con
1. Download Size?
1. Performance?

## OpenQuestions

**Comment by DanielFroehlich** [comment]
As we have very limited ressources, I vote for going with Ionic/Angular simply for the fact that Column and Ortwin do have expierence with that. Everything else would mean we have to go thorugh a learning curve, which we dont have the budget for.
